#!/bin/env bash

# This script takes a video file and makes a gif with it
# It was inspired from https://homehack.nl/create-animated-gifs-from-mp4-with-ffmpeg/

# Default values
fps=30

help() {
  echo "Usage: $(basename $0) [-h] -i VIDEO_FILE [-f FPS]"
  echo "Options:"
  echo "  -h,    Display this help message"
  echo "  -i,    Input video file"
  echo "  -f,    Set the custom fps (default 30)"
  exit 0
}

# Parse command-line options
while getopts ":hi:f:" opt; do
  case $opt in
    h) help ;;
    i) input_video=$OPTARG ;;
    f) fps=$OPTARG ;;
    \?) echo "Invalid option: -$OPTARG" >&2; exit 1 ;;
  esac
done


# Main
# generate temporary pallete
ffmpeg -i "${input_video}" -filter_complex "[0:v] palettegen" "tmp_pallete.png"

filename=$(basename ${input_video})

# generate gif
ffmpeg -i "${input_video}" -i "tmp_pallete.png" -r $fps -filter_complex "[0:v][1:v] paletteuse" "${filename%.*}.gif"

# delete temporary pallete
rm "tmp_pallete.png"
